language: generic

addons:
  snaps:
    - name: hugo
      channel: extended

jobs:
  include:
    - stage: Docs
      before_install:
        - cd site
        - hugo version
      install:
        - npm install -D --save autoprefixer
        - npm install -D --save postcss
        - npm install -D --save postcss-cli
      script: 
        - hugo
      deploy:
        provider: pages
        token: $GITHUB_TOKEN
        local-dir: site/public
        skip-cleanup: true
