language: generic

jobs:
  include:
    - stage: Docs
      install:
        - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.78.1/hugo_0.78.1_Linux-64bit.deb
        - sudo dpkg -i hugo_0.78.1_Linux-64bit.deb
        - rm hugo_0.78.1_Linux-64bit.deb
        - cd site
        - npm install -D --save autoprefixer
        - npm install -D --save postcss
        - npm install -D --save postcss-cli
      script: 
        - hugo
      deploy:
        provider: pages
        token: $GITHUB_TOKEN
        local-dir: site/public
        skip-cleanup: true
