# Operational parameters
params:
  ipap:
    min: 3
    max: 35
    default: 15
  epap:
    min: 2
    max: 34
    default: 5
  freq:
    min: 2
    max: 30
    default: 15
  trigger:
    min: 2
    max: 12
    default: 5
  inhale:
    min: 1
    max: 5
    default: 1
  exhale:
    min: 1
    max: 5
    default: 2

# Alarm limits
alarms:
  pressure:
    min: 2
    max: 35
  volume:
    min: 2
    max: 12
  oxygen:
    min: 21
    max: 100
  freq:
    min: 2
    max: 40
