"""Events that can occur during the app's operation."""

# Parameters view
IPAP_SLIDER_PARAMS = "-IPAP_SLIDER_PARAMS-"
EPAP_SLIDER_PARAMS = "-EPAP_SLIDER_PARAMS-"
FREQ_SLIDER_PARAMS = "-FREQ_SLIDER_PARAMS-"
TRIGGER_SLIDER_PARAMS = "-TRIGGER_SLIDER_PARAMS-"
IE_SLIDER_PARAMS = "-IE_SLIDER_PARAMS-"
START_BUTTON_PARAMS = "-START_BUTTON_PARAMS-"

# Operation view
LOCK_SCREEN_BUTTON_OPER = "-LOCK_SCREEN_BUTTON_OPER-"

IPAP_SLIDER_OPER = "-IPAP_SLIDER_OPER-"
EPAP_SLIDER_OPER = "-EPAP_SLIDER_OPER-"
FREQ_SLIDER_OPER = "-FREQ_SLIDER_OPER-"
TRIGGER_SLIDER_OPER = "-TRIGGER_SLIDER_OPER-"
IE_SLIDER_OPER = "-IE_SLIDER_OPER-"

PRESSURE_MIN_SLIDER_OPER = "-PRESSURE_MIN_SLIDER_OPER-"
PRESSURE_MAX_SLIDER_OPER = "-PRESSURE_MAX_SLIDER_OPER-"
VOLUME_MIN_SLIDER_OPER = "-VOLUME_MIN_SLIDER_OPER-"
VOLUME_MAX_SLIDER_OPER = "-VOLUME_MAX_SLIDER_OPER-"
OXYGEN_MIN_SLIDER_OPER = "-OXYGEN_MIN_SLIDER_OPER-"
OXYGEN_MAX_SLIDER_OPER = "-OXYGEN_MAX_SLIDER_OPER-"
FREQ_MAX_SLIDER_OPER = "-FREQ_MAX_SLIDER_OPER-"
APPLY_ALARMS_BUTTON_OPER = "-APPLY_ALARMS_BUTTON_OPER-"

SILENCE_ALARMS_BUTTON_OPER = "-SILENCE_ALARMS_BUTTON_OPER-"

# ZeroMQ messages
ZMQ_CHECK = "-ZMQ_CHECK-"
ZMQ_READING = "-ZMQ_READING-"
ZMQ_CYCLE = "-ZMQ_CYCLE-"
ZMQ_ALARM = "-ZMQ_ALARM-"
ZMQ_OPER_MODE = "-ZMQ_OPER_MODE-"
